services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
      # Port 9000 is legacy (HTTP). Enable only if you need it.
      # - 9000:9000
      # Port 8000 is only needed if you intend to use Edge Agents.
      # - 8000:8000

volumes:
  portainer_data:
    name: portainer_data

networks:
  default:
    name: portainer_network
