apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "<terraform output -raw identity_client_id>"
---
apiVersion: v1
kind: Pod
metadata:
  name: wi-test
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload-identity-sa
  containers:
  - name: wi-test
    image: mcr.microsoft.com/azure-cli
    command: ["sleep", "3600"]
