apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-app
  namespace: custom-app
  annotations:
    # IRSA: EKS 會將此 ServiceAccount 與 IAM Role 綁定
    # Pod 取得的 Token 會自動對應到這個 Role 的權限
    eks.amazonaws.com/role-arn: arn:aws:iam::661515655645:role/infra-lab-dev-custom-app-role
