apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/changken/infra-lab
    targetRevision: HEAD
    path: terraform/envs/aws-eks/k8s/custom-app
  destination:
    server: https://kubernetes.default.svc
    namespace: custom-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
